ETISS 0.8.0: etiss::SimpleMemSystem Class Reference
etiss::SimpleMemSystem Class Reference
simple etiss:System implementation for testing
#include <SimpleMemSystem.h>
Public Member Functions
SimpleMemSystem (uint32_t rom_start, uint32_t rom_size, uint32_t ram_start, uint32_t ram_size)
SimpleMemSystem (void)
virtual ~SimpleMemSystem (void)
etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)
Instruction read operation.
etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Instruction write operation.
etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data read operation.
etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data write operation.
etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug read operation.
etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug write operation.
void syncTime (ETISS_CPU *cpu)
Synchronize simulation time.
etiss::int8 load_elf (const char *file)
loads a binary image from a file to the given address
etiss::uint64 get_startaddr (void)
etiss::int8 add_memsegment (std::unique_ptr< MemSegment > mseg, const void *raw_data, size_t file_size_bytes)
SimpleMemSystem (uint32_t rom_start, uint32_t rom_size, uint32_t ram_start, uint32_t ram_size)
SimpleMemSystem (void)
virtual ~SimpleMemSystem (void)
etiss::int32 iread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint32 len)
Instruction read operation.
etiss::int32 iwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Instruction write operation.
etiss::int32 dread (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data read operation.
etiss::int32 dwrite (ETISS_CPU *cpu, etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Data write operation.
etiss::int32 dbg_read (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug read operation.
etiss::int32 dbg_write (etiss::uint64 addr, etiss::uint8 *buf, etiss::uint32 len)
Debug write operation.
void syncTime (ETISS_CPU *cpu)
Synchronize simulation time.
etiss::int8 load_elf (const char *file)
loads a binary image from a file to the given address
etiss::uint64 get_startaddr (void)
etiss::int8 add_memsegment (std::unique_ptr< MemSegment > mseg, const void *raw_data, size_t file_size_bytes)
Public Member Functions inherited from etiss::System
virtual ~System ()
virtual ~System ()
Private Attributes
std::vector< std::unique_ptr< MemSegment > > msegs_ {}
etiss::uint64 start_addr_ { 0 }
std::vector< uint8 > ram_mem_ {}
std::vector< uint8 > rom_mem_ {}
const etiss::uint64 rom_start_
const etiss::uint64 ram_start_
const etiss::uint64 rom_size_
const etiss::uint64 ram_size_
bool _print_ibus_access
bool _print_dbus_access
bool _print_dbgbus_access
bool _print_to_file
int message_max_cnt
std::ofstream trace_file_dbus_
Detailed Description
simple etiss:System implementation for testing
Definition at line 130 of file SimpleMemSystem.h.
Constructor & Destructor Documentation
SimpleMemSystem() [1/4]
SimpleMemSystem::SimpleMemSystem (uint32_t rom_start, uint32_t rom_size, uint32_t ram_start, uint32_t ram_size)
Definition at line 213 of file SimpleMemSystem.cpp.
References _print_dbgbus_access, _print_dbus_access, _print_ibus_access, _print_to_file, etiss::cfg(), etiss::Configuration::get(), message_max_cnt, ram_mem_, rom_mem_, and trace_file_dbus_.
SimpleMemSystem() [2/4]
SimpleMemSystem::SimpleMemSystem (void)
Definition at line 231 of file SimpleMemSystem.cpp.
~SimpleMemSystem() [1/2]
virtual etiss::SimpleMemSystem::~SimpleMemSystem (void) inline virtual
Definition at line 136 of file SimpleMemSystem.h.
References msegs_.
SimpleMemSystem() [3/4]
etiss::SimpleMemSystem::SimpleMemSystem (uint32_t rom_start, uint32_t rom_size, uint32_t ram_start, uint32_t ram_size)
SimpleMemSystem() [4/4]
etiss::SimpleMemSystem::SimpleMemSystem (void)
~SimpleMemSystem() [2/2]
virtual etiss::SimpleMemSystem::~SimpleMemSystem (void) inline virtual
Definition at line 136 of file SimpleMemSystem.h.
References msegs_.
Member Function Documentation
add_memsegment() [1/2]
etiss::int8 SimpleMemSystem::add_memsegment (std::unique_ptr< MemSegment > mseg, const void * raw_data, size_t file_size_bytes)
Definition at line 189 of file SimpleMemSystem.cpp.
References etiss::INFO, etiss::log(), msegs_, and etiss::MemSegment::start_addr_.
Referenced by load_elf().
add_memsegment() [2/2]
etiss::int8 etiss::SimpleMemSystem::add_memsegment (std::unique_ptr< MemSegment > mseg, const void * raw_data, size_t file_size_bytes)
dbg_read() [1/2]
etiss::int32 SimpleMemSystem::dbg_read (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug read operation.
This method should implement a debug read operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Note
The read debug operation is used for the instruction fetches required for generating the code blocks.
Parameters
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 398 of file SimpleMemSystem.cpp.
References AccessError(), etiss::ERROR, etiss::log(), memcpy(), msegs_, etiss::mm::NOERROR, ram_mem_, ram_start_, rom_mem_, and rom_start_.
dbg_read() [2/2]
etiss::int32 etiss::SimpleMemSystem::dbg_read (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug read operation.
This method should implement a debug read operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Note
The read debug operation is used for the instruction fetches required for generating the code blocks.
Parameters
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
dbg_write() [1/2]
etiss::int32 etiss::SimpleMemSystem::dbg_write (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug write operation.
This method should implement a debug write operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Parameters
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred
Implements etiss::System.
dbg_write() [2/2]
etiss::int32 SimpleMemSystem::dbg_write (etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Debug write operation.
This method should implement a debug write operation. The debug operations are used for data access that should not influence the simulation time. To indicate an error a non 0 value should be returned.
Parameters
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred
Implements etiss::System.
Definition at line 452 of file SimpleMemSystem.cpp.
References AccessError(), etiss::ERROR, etiss::log(), memcpy(), msegs_, etiss::mm::NOERROR, ram_mem_, and ram_start_.
dread() [1/2]
etiss::int32 SimpleMemSystem::dread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data read operation.
This method should implement a data read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 277 of file SimpleMemSystem.cpp.
References _print_dbus_access, _print_to_file, AccessError(), etiss::ERROR, ETISS_CPU::instructionPointer, etiss::log(), memcpy(), msegs_, etiss::mm::NOERROR, ram_mem_, ram_start_, rom_mem_, rom_start_, Trace(), and trace_file_dbus_.
dread() [2/2]
etiss::int32 etiss::SimpleMemSystem::dread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data read operation.
This method should implement a data read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the data should be read.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
dwrite() [1/2]
etiss::int32 SimpleMemSystem::dwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data write operation.
This method should implement a data write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 342 of file SimpleMemSystem.cpp.
References _print_dbus_access, _print_to_file, AccessError(), etiss::ERROR, ETISS_CPU::instructionPointer, etiss::log(), memcpy(), msegs_, etiss::mm::NOERROR, ram_mem_, ram_start_, Trace(), and trace_file_dbus_.
dwrite() [2/2]
etiss::int32 etiss::SimpleMemSystem::dwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Data write operation.
This method should implement a data write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the data should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the data in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
get_startaddr() [1/2]
etiss::uint64 etiss::SimpleMemSystem::get_startaddr (void) inline
Definition at line 159 of file SimpleMemSystem.h.
References start_addr_.
get_startaddr() [2/2]
etiss::uint64 etiss::SimpleMemSystem::get_startaddr (void) inline
Definition at line 159 of file SimpleMemSystem.h.
References start_addr_.
iread() [1/2]
etiss::int32 etiss::SimpleMemSystem::iread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len) virtual
Instruction read operation.
This method should implement an instruction read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the instruction should be read.
len The length of the instruction in bytes.
Returns
0 if no error occurred
Implements etiss::System.
iread() [2/2]
etiss::int32 SimpleMemSystem::iread (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint32 len) virtual
Instruction read operation.
This method should implement an instruction read operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface.
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address from which the instruction should be read.
len The length of the instruction in bytes.
Returns
0 if no error occurred
Implements etiss::System.
Definition at line 233 of file SimpleMemSystem.cpp.
References AccessError(), ETISS_CPU::instructionPointer, msegs_, etiss::mm::NOERROR, rom_mem_, and rom_start_.
iwrite() [1/2]
etiss::int32 SimpleMemSystem::iwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Instruction write operation.
This method should implement an instruction write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the instruction should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the instruction in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
Definition at line 257 of file SimpleMemSystem.cpp.
References etiss::log(), and etiss::VERBOSE.
iwrite() [2/2]
etiss::int32 etiss::SimpleMemSystem::iwrite (ETISS_CPU * cpu, etiss::uint64 addr, etiss::uint8 * buf, etiss::uint32 len) virtual
Instruction write operation.
This method should implement an instruction write operation. To indicate an error a non 0 value should be returned. The CPU time needs to be increased according to the delay of this instruction operation.
Note
Normally this method can be implemented as an empty method that only returns an error value. Because of the translating nature of ETISS all instruction operations are out of order an will be performed via the debug interface
Parameters
cpu Pointer to the CPU structure, that requested this operation.
addr The address to which the instruction should be written.
buf Pointer to the buffer, that contains the instruction.
len The length of the instruction in bytes.
Returns
0 if no error occurred.
Implements etiss::System.
load_elf() [1/2]
etiss::int8 SimpleMemSystem::load_elf (const char * file)
loads a binary image from a file to the given address
Definition at line 84 of file SimpleMemSystem.cpp.
References add_memsegment(), etiss::cfg(), etiss::ERROR, etiss::FATALERROR, etiss::log(), msegs_, ram_mem_, ram_size_, ram_start_, etiss::MemSegment::READ, rom_mem_, rom_size_, rom_start_, etiss::Configuration::set(), start_addr_, etiss::WARNING, and etiss::MemSegment::WRITE.
load_elf() [2/2]
etiss::int8 etiss::SimpleMemSystem::load_elf (const char * file)
loads a binary image from a file to the given address
syncTime() [1/2]
void SimpleMemSystem::syncTime (ETISS_CPU * cpu) virtual
Synchronize simulation time.
This method should implement the synchronization between the simulation time of the system and the CPU. This function call should allow the system to catch up with the CPU.
See also
etiss::ETISS_CPU
Parameters
cpu Pointer to the CPU structure, for which the synchronization should be performed.
Implements etiss::System.
Definition at line 501 of file SimpleMemSystem.cpp.
syncTime() [2/2]
void etiss::SimpleMemSystem::syncTime (ETISS_CPU * cpu) virtual
Synchronize simulation time.
This method should implement the synchronization between the simulation time of the system and the CPU. This function call should allow the system to catch up with the CPU.
See also
etiss::ETISS_CPU
Parameters
cpu Pointer to the CPU structure, for which the synchronization should be performed.
Implements etiss::System.
Member Data Documentation
_print_dbgbus_access
bool etiss::SimpleMemSystem::_print_dbgbus_access private
Definition at line 177 of file SimpleMemSystem.h.
Referenced by SimpleMemSystem().
_print_dbus_access
bool etiss::SimpleMemSystem::_print_dbus_access private
Definition at line 176 of file SimpleMemSystem.h.
Referenced by dread(), dwrite(), and SimpleMemSystem().
_print_ibus_access
bool etiss::SimpleMemSystem::_print_ibus_access private
Definition at line 175 of file SimpleMemSystem.h.
Referenced by SimpleMemSystem().
_print_to_file
bool etiss::SimpleMemSystem::_print_to_file private
Definition at line 178 of file SimpleMemSystem.h.
Referenced by dread(), dwrite(), and SimpleMemSystem().
message_max_cnt
int etiss::SimpleMemSystem::message_max_cnt private
Definition at line 180 of file SimpleMemSystem.h.
Referenced by SimpleMemSystem().
msegs_
std::vector< std::unique_ptr< MemSegment > > etiss::SimpleMemSystem::msegs_ {} private
Definition at line 163 of file SimpleMemSystem.h.
Referenced by add_memsegment(), dbg_read(), dbg_write(), dread(), dwrite(), iread(), load_elf(), and ~SimpleMemSystem().
ram_mem_
std::vector< uint8 > etiss::SimpleMemSystem::ram_mem_ {} private
Definition at line 167 of file SimpleMemSystem.h.
Referenced by dbg_read(), dbg_write(), dread(), dwrite(), load_elf(), and SimpleMemSystem().
ram_size_
const etiss::uint64 etiss::SimpleMemSystem::ram_size_ private
Definition at line 173 of file SimpleMemSystem.h.
Referenced by load_elf().
ram_start_
const etiss::uint64 etiss::SimpleMemSystem::ram_start_ private
Definition at line 171 of file SimpleMemSystem.h.
Referenced by dbg_read(), dbg_write(), dread(), dwrite(), and load_elf().
rom_mem_
std::vector< uint8 > etiss::SimpleMemSystem::rom_mem_ {} private
Definition at line 168 of file SimpleMemSystem.h.
Referenced by dbg_read(), dread(), iread(), load_elf(), and SimpleMemSystem().
rom_size_
const etiss::uint64 etiss::SimpleMemSystem::rom_size_ private
Definition at line 172 of file SimpleMemSystem.h.
Referenced by load_elf().
rom_start_
const etiss::uint64 etiss::SimpleMemSystem::rom_start_ private
Definition at line 170 of file SimpleMemSystem.h.
Referenced by dbg_read(), dread(), iread(), and load_elf().
start_addr_
etiss::uint64 etiss::SimpleMemSystem::start_addr_ { 0 } private
Definition at line 165 of file SimpleMemSystem.h.
Referenced by get_startaddr(), and load_elf().
trace_file_dbus_
std::ofstream etiss::SimpleMemSystem::trace_file_dbus_ private
Definition at line 182 of file SimpleMemSystem.h.
Referenced by dread(), dwrite(), and SimpleMemSystem().
The documentation for this class was generated from the following files:
include/etiss/SimpleMemSystem.h
/home/runner/work/etiss-private/etiss-private/src/SimpleMemSystem.cpp