ETISS 0.8.0: etiss::MemSegment Class Reference
etiss::MemSegment Class Reference
#include <SimpleMemSystem.h>
Public Types
enum ACCESS { READ, WRITE, READ, WRITE }
enum ACCESS { READ, WRITE, READ, WRITE }
typedef enum etiss::MemSegment::ACCESS access_t
typedef enum etiss::MemSegment::ACCESS access_t
Public Member Functions
MemSegment (etiss::uint64 start_addr, etiss::uint64 size, access_t mode, const std::string name, etiss::uint8 *mem=nullptr)
virtual ~MemSegment (void)
void load (const void *data, size_t file_size_bytes)
bool addr_in_range (etiss::uint64 addr) const
bool payload_in_range (etiss::uint64 addr, etiss::uint64 payload_size) const
MemSegment (etiss::uint64 start_addr, etiss::uint64 size, access_t mode, const std::string name, etiss::uint8 *mem=nullptr)
virtual ~MemSegment (void)
void load (const void *data, size_t file_size_bytes)
bool addr_in_range (etiss::uint64 addr) const
bool payload_in_range (etiss::uint64 addr, etiss::uint64 payload_size) const
Public Attributes
etiss::uint8 * mem_
const std::string name_
const etiss::uint64 start_addr_
const etiss::uint64 end_addr_
const etiss::uint64 size_
const access_t mode_
Private Attributes
bool self_allocated_ { false }
Detailed Description
Definition at line 64 of file SimpleMemSystem.h.
Member Typedef Documentation
access_t [1/2]
typedef enum etiss::MemSegment::ACCESS etiss::MemSegment::access_t
access_t [2/2]
typedef enum etiss::MemSegment::ACCESS etiss::MemSegment::access_t
Member Enumeration Documentation
ACCESS [1/2]
enum etiss::MemSegment::ACCESS
Enumerator
READ
WRITE
READ
WRITE
Definition at line 69 of file SimpleMemSystem.h.
ACCESS [2/2]
enum etiss::MemSegment::ACCESS
Enumerator
READ
WRITE
READ
WRITE
Definition at line 69 of file SimpleMemSystem.h.
Constructor & Destructor Documentation
MemSegment() [1/2]
etiss::MemSegment::MemSegment (etiss::uint64 start_addr, etiss::uint64 size, access_t mode, const std::string name, etiss::uint8 * mem = nullptr) inline
Definition at line 83 of file SimpleMemSystem.h.
References mem_, and self_allocated_.
~MemSegment() [1/2]
virtual etiss::MemSegment::~MemSegment (void) inline virtual
Definition at line 98 of file SimpleMemSystem.h.
References mem_, and self_allocated_.
MemSegment() [2/2]
etiss::MemSegment::MemSegment (etiss::uint64 start_addr, etiss::uint64 size, access_t mode, const std::string name, etiss::uint8 * mem = nullptr) inline
Definition at line 83 of file SimpleMemSystem.h.
References mem_, and self_allocated_.
~MemSegment() [2/2]
virtual etiss::MemSegment::~MemSegment (void) inline virtual
Definition at line 98 of file SimpleMemSystem.h.
References mem_, and self_allocated_.
Member Function Documentation
addr_in_range() [1/2]
bool etiss::MemSegment::addr_in_range (etiss::uint64 addr) const inline
Definition at line 112 of file SimpleMemSystem.h.
References end_addr_, and start_addr_.
Referenced by payload_in_range().
addr_in_range() [2/2]
bool etiss::MemSegment::addr_in_range (etiss::uint64 addr) const inline
Definition at line 112 of file SimpleMemSystem.h.
References end_addr_, and start_addr_.
load() [1/2]
void etiss::MemSegment::load (const void * data, size_t file_size_bytes) inline
Definition at line 104 of file SimpleMemSystem.h.
References mem_, memcpy(), and size_.
load() [2/2]
void etiss::MemSegment::load (const void * data, size_t file_size_bytes) inline
Definition at line 104 of file SimpleMemSystem.h.
References mem_, memcpy(), and size_.
payload_in_range() [1/2]
bool etiss::MemSegment::payload_in_range (etiss::uint64 addr, etiss::uint64 payload_size) const inline
Definition at line 117 of file SimpleMemSystem.h.
References addr_in_range(), and end_addr_.
payload_in_range() [2/2]
bool etiss::MemSegment::payload_in_range (etiss::uint64 addr, etiss::uint64 payload_size) const inline
Definition at line 117 of file SimpleMemSystem.h.
References addr_in_range(), and end_addr_.
Member Data Documentation
end_addr_
const etiss::uint64 etiss::MemSegment::end_addr_
Definition at line 79 of file SimpleMemSystem.h.
Referenced by addr_in_range(), and payload_in_range().
mem_
etiss::uint8 * etiss::MemSegment::mem_
Definition at line 75 of file SimpleMemSystem.h.
Referenced by load(), MemSegment(), and ~MemSegment().
mode_
const access_t etiss::MemSegment::mode_
Definition at line 81 of file SimpleMemSystem.h.
name_
const std::string etiss::MemSegment::name_
Definition at line 77 of file SimpleMemSystem.h.
self_allocated_
bool etiss::MemSegment::self_allocated_ { false } private
Definition at line 66 of file SimpleMemSystem.h.
Referenced by MemSegment(), and ~MemSegment().
size_
const etiss::uint64 etiss::MemSegment::size_
Definition at line 80 of file SimpleMemSystem.h.
Referenced by load().
start_addr_
const etiss::uint64 etiss::MemSegment::start_addr_
Definition at line 78 of file SimpleMemSystem.h.
Referenced by etiss::SimpleMemSystem::add_memsegment(), and addr_in_range().
The documentation for this class was generated from the following file:
include/etiss/SimpleMemSystem.h